In [70]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.nn.functional as F
from torchvision import datasets
import matplotlib.pyplot as plt
import os
import csv
from sklearn.model_selection import train_test_split

In [71]:
PATH_D = "Series temporales/DNI/"
NUM_S = 3
SENSORS = ["S1", "S3", "S4"]

In [73]:
def get_series():
    series = []
    for i in range(NUM_S):
        validos = sorted(os.listdir(PATH_D + SENSORS[i] + "/series/validas"))
        invalidos = sorted(os.listdir(PATH_D + SENSORS[i] + "/series/no validas"))
        series.append([validos,invalidos])
    return series

In [74]:
print(get_series()[0][1])

['2013-225', '2013-42', '2014-269', '2014-270', '2014-271', '2014-272', '2014-273', '2014-274', '2014-275', '2014-276', '2014-277', '2014-278', '2014-279', '2014-280', '2014-281', '2014-282', '2014-283', '2014-284', '2014-285', '2014-286', '2014-287', '2014-288', '2014-289', '2014-290', '2014-291', '2014-292', '2014-293', '2014-294', '2014-295', '2014-296', '2014-297', '2014-298', '2014-299', '2014-300', '2014-301', '2014-302', '2014-303', '2014-304', '2014-305', '2014-306', '2014-307', '2014-308', '2014-309', '2014-310', '2014-311', '2014-312', '2014-313', '2014-314', '2014-315', '2014-316', '2014-317', '2014-318', '2014-319', '2014-320', '2014-321', '2014-322', '2014-323', '2014-324', '2014-325', '2014-326', '2014-327', '2014-328', '2014-329', '2014-330', '2014-357', '2014-65', '2014-8', '2015-118', '2015-119', '2015-120', '2015-20', '2015-293', '2015-302', '2015-303', '2016-110', '2016-111', '2016-202', '2016-203', '2016-204', '2016-205', '2016-206', '2016-207', '2016-208', '2016-3'

In [78]:
def search_day(year,day,series):
    name = str(year) + '-' + str(day)
    param = []
    for i in range(NUM_S):
        for j in range(2):
            if name in series[i][j]:
                param.append(float(j))
    return param

In [79]:
series = get_series()

In [80]:
print(search_day(2015,68,series))

[0.0, 0.0, 0.0]


In [81]:
for y in range(2013,2020):
    for d in range(1,366):
        if (len(search_day(y,d,series)) != NUM_S):
            print(str(y)+"-"+str(d))

2019-182
2019-183
2019-184
2019-185
2019-186
2019-187
2019-188
2019-189
2019-190
2019-191
2019-192
2019-193
2019-194
2019-195
2019-196
2019-197
2019-198
2019-199
2019-200
2019-201
2019-202
2019-203
2019-204
2019-205
2019-206
2019-207
2019-208
2019-209
2019-210
2019-211
2019-212
2019-213
2019-214
2019-215
2019-216
2019-217
2019-218
2019-219
2019-220
2019-221
2019-222
2019-223
2019-224
2019-225
2019-226
2019-227
2019-228
2019-229
2019-230
2019-231
2019-232
2019-233
2019-234
2019-235
2019-236
2019-237
2019-238
2019-239
2019-240
2019-241
2019-242
2019-243
2019-244
2019-245
2019-246
2019-247
2019-248
2019-249
2019-250
2019-251
2019-252
2019-253
2019-254
2019-255
2019-256
2019-257
2019-258
2019-259
2019-260
2019-261
2019-262
2019-263
2019-264
2019-265
2019-266
2019-267
2019-268
2019-269
2019-270
2019-271
2019-272
2019-273
2019-274
2019-275
2019-276
2019-277
2019-278
2019-279
2019-280
2019-281
2019-282
2019-283
2019-284
2019-285
2019-286
2019-287
2019-288
2019-289
2019-290
2019-291
2019-292
2

In [82]:
def reshape_series(series):
    series_reshaped = []
    for y in range(2013,2020):
        for d in range(1,366):
            labels = search_day(y,d,series)
            if len(labels) == NUM_S:
                series_reshaped.append([str(y)+'-'+str(d),labels])

    return series_reshaped

In [83]:
series = reshape_series(series)
print(series)

[['2013-1', [0.0, 0.0, 0.0]], ['2013-2', [0.0, 0.0, 0.0]], ['2013-3', [0.0, 0.0, 0.0]], ['2013-4', [0.0, 0.0, 0.0]], ['2013-5', [0.0, 0.0, 0.0]], ['2013-6', [0.0, 0.0, 0.0]], ['2013-7', [0.0, 0.0, 0.0]], ['2013-8', [0.0, 0.0, 0.0]], ['2013-9', [0.0, 0.0, 0.0]], ['2013-10', [0.0, 0.0, 0.0]], ['2013-11', [0.0, 0.0, 0.0]], ['2013-12', [0.0, 0.0, 0.0]], ['2013-13', [0.0, 0.0, 0.0]], ['2013-14', [0.0, 0.0, 0.0]], ['2013-15', [0.0, 0.0, 0.0]], ['2013-16', [0.0, 0.0, 0.0]], ['2013-17', [0.0, 0.0, 1.0]], ['2013-18', [0.0, 0.0, 0.0]], ['2013-19', [0.0, 0.0, 1.0]], ['2013-20', [0.0, 0.0, 1.0]], ['2013-21', [0.0, 0.0, 1.0]], ['2013-22', [0.0, 0.0, 0.0]], ['2013-23', [0.0, 0.0, 0.0]], ['2013-24', [0.0, 0.0, 0.0]], ['2013-25', [0.0, 0.0, 0.0]], ['2013-26', [0.0, 0.0, 0.0]], ['2013-27', [0.0, 0.0, 0.0]], ['2013-28', [0.0, 0.0, 0.0]], ['2013-29', [0.0, 0.0, 0.0]], ['2013-30', [0.0, 0.0, 0.0]], ['2013-31', [0.0, 1.0, 0.0]], ['2013-32', [0.0, 1.0, 0.0]], ['2013-33', [0.0, 0.0, 0.0]], ['2013-34', [0.0, 

In [84]:
def get_points(path):
    with open(path, newline='',encoding="utf-8") as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        for row in reader:
            if not '' in row:
                y = [float(x) for x in row]
            else:
                y = []
                for x in row:
                    y.append(float('2000')) if x == '' else y.append(float(x))
    return y

In [85]:
class dni(Dataset):
    def __init__(self, root_dir, files):
        self.root_dir = root_dir
        self.files = files              

    def __len__(self):
        return len(self.files)
    
    def __getitem__(self, index):
        series = []
        item = self.files[index]
        for i in range(NUM_S):
            path = self.root_dir + SENSORS[i] + "/series" 
            path += ("/validas" if item[1][i] == 0 else "/no validas")
            path += "/" + item[0]
            series.append(get_points(path))

        return (torch.tensor([series]), torch.tensor([item[1][0]]))


In [86]:
train_series, test_series = train_test_split(series)

In [87]:
print(len(train_series), len(test_series))

1778 593


In [88]:
print(len(series))

2371


In [89]:
train_ds = dni(PATH_D,train_series)
test_ds = dni(PATH_D,test_series)

In [90]:
print(train_ds[0])

(tensor([[[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
            0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   9.4215,  77.9217,
           34.6927, 251.6074, 208.9850, 273.4950, 379.8410, 533.9666, 556.8885,
           53.2322,  60.6632, 377.6172, 617.1059, 582.1744, 435.3737, 706.8233,
          723.5583, 728.3389, 725.3288, 762.2118, 776.6241, 782.8956, 758.1235,
          809.5886, 775.7292, 729.5164, 824.6254, 806.6326, 808.1706, 834.1475,
          838.2014, 822.8644, 812.2103, 752.3097, 771.9631, 749.3293, 746.2090,
          743.7180, 742.6147, 702.0573,

In [21]:
print(train_ds[0][0].shape)

torch.Size([1, 1, 144])


In [91]:
batch_size = 1
train_load = DataLoader(train_ds,batch_size=batch_size,shuffle=True,drop_last=True)
test_load = DataLoader(test_ds,batch_size=batch_size,shuffle=True,drop_last=True)

In [23]:
# for input, label in train_load:
#     print(input.shape)

In [92]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using cpu device


In [103]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN,self).__init__()
        self.conv1 = nn.Conv2d(1,3,3)
        self.conv2 = nn.Conv2d(3,9,3)
        self.pool = nn.MaxPool2d((1,2))
        self.dense1 = nn.Linear(9*3*34,50)        #144-2=142
        self.dense2 = nn.Linear(50,1)             #142/2=71
        self.flatten = nn.Flatten()               #71-2=69
                                                  #69/2=34
                                                  #9*3*34= 918
    def forward(self, x):
        x = F.pad(x, (0, 0, 1, 1), mode='circular')
        x = self.pool(F.relu(self.conv1(x)))
        x = F.pad(x, (0, 0, 1, 1), mode='circular')
        x = self.pool(F.relu(self.conv2(x)))
        #print(x.shape)
        #x = x.view((batch_size,9*3*34))
        x = self.flatten(x)
        x = F.sigmoid(self.dense1(x))
        x = self.dense2(x)
        return x

In [94]:
labels = np.zeros((len(train_series),NUM_S),dtype=float)
for i in range(labels.shape[0]):
    labels[i] = train_series[i][1]

labels = torch.tensor(labels)
print(labels)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 0.],
        ...,
        [0., 1., 0.],
        [0., 0., 0.],
        [0., 1., 0.]], dtype=torch.float64)


In [105]:
# Cuenta positivos y negativos por clase
num_pos = labels.sum(dim=0)
num_neg = labels.shape[0] - num_pos

# Calcula el pos_weight
pos_weight = num_neg / num_pos
pos_weight = 2*pos_weight[0]
print(pos_weight)

tensor(10.1781, dtype=torch.float64)


In [99]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    # Set the model to training mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        # if (batch +1) % 100 == 0:
        #     loss, current = loss.item(), batch * batch_size + len(X)
        #     print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test_loop(dataloader, model, loss_fn):
    # Set the model to evaluation mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    positive_real, positive_pred, test_loss, correct, correct_pos = 0, 0, 0, 0, 0

    # Evaluating the model with torch.no_grad() ensures that no gradients are computed during test mode
    # also serves to reduce unnecessary gradient computations and memory usage for tensors with requires_grad=True
    with torch.no_grad():
        for X, y in dataloader:
            pred = F.sigmoid(model(X))
            test_loss += loss_fn(pred, y).item()
            #print("PRED:",pred.round(),y)

            pred_pos = (pred.round() == 1.0)
            real_pos = (y == 1.0)
            positive_pred += pred_pos.type(torch.float).sum().item()
            positive_real += real_pos.type(torch.float).sum().item()
            correct_pos += torch.bitwise_and(pred_pos,real_pos).type(torch.float).sum().item()
            correct += (pred.round() == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= NUM_S*size
    print(f"Test Error: \nAccuracy: \t {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f}")
    print(f"Precision: \t {(100*correct_pos/positive_pred):>0.1f}%")
    print(f"Recall: \t {(100*correct_pos/positive_real):>0.1f}%")


In [119]:
a = torch.tensor([True,True,False])
b = torch.tensor([False,True,False])


print(torch.bitwise_and(a,b))

tensor([False,  True, False])


In [106]:
model = CNN().to(device)

criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = torch.optim.Adam(model.parameters(),lr=0.0001)

epochs = 50
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_load, model, criterion, optimizer)
    test_loop(test_load, model, criterion)
print("Done!")


Epoch 1
-------------------------------
Test Error: 
Accuracy: 	 24.1%, Avg loss: 1.453368
Precision: 	 35.6%
Recall: 	 80.0%
Epoch 2
-------------------------------
Test Error: 
Accuracy: 	 23.8%, Avg loss: 1.424361
Precision: 	 35.4%
Recall: 	 84.0%
Epoch 3
-------------------------------
Test Error: 
Accuracy: 	 24.7%, Avg loss: 1.405560
Precision: 	 38.2%
Recall: 	 86.0%
Epoch 4
-------------------------------
Test Error: 
Accuracy: 	 27.2%, Avg loss: 1.386909
Precision: 	 47.5%
Recall: 	 85.0%
Epoch 5
-------------------------------
Test Error: 
Accuracy: 	 28.0%, Avg loss: 1.376346
Precision: 	 51.5%
Recall: 	 85.0%
Epoch 6
-------------------------------
Test Error: 
Accuracy: 	 27.0%, Avg loss: 1.369280
Precision: 	 46.4%
Recall: 	 85.0%
Epoch 7
-------------------------------
Test Error: 
Accuracy: 	 28.8%, Avg loss: 1.356316
Precision: 	 56.5%
Recall: 	 83.0%
Epoch 8
-------------------------------
Test Error: 
Accuracy: 	 28.3%, Avg loss: 1.353724
Precision: 	 53.5%
Recall: 

KeyboardInterrupt: 

In [36]:
# def test_loop(dataloader,model):
#     model.eval()
#     correct = 0
#     total = 0
#     with torch.no_grad():
#         for data in dataloader:
#             images, labels = data
#             outputs = model(images)
#             # _, predicted = torch.max(outputs.data, 1)
#             total += labels.size(0)
#             correct += (outputs.round() == labels).sum().item()

#     print('Accuracy of the network on the 10000 test images: %d %%' % (
#         100 * correct / (3*total)))

In [37]:
# for epoch in range(10):  # loop over the dataset multiple times
#     model.train()
#     running_loss = 0.0
#     for i, data in enumerate(train_load, 0):
#         # get the inputs
#         inputs, labels = data

#         # zero the parameter gradients

#         # forward + backward + optimize
#         outputs = model(inputs)
#         loss = criterion(outputs, labels)
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()

#         # print statistics
#         running_loss += loss.item()
#         # if i % 100 == 99:    # print every 100 mini-batches
#         #     print('[%d, %5d] loss: %.3f' %
#         #           (epoch + 1, i + 1, running_loss / 100))
#         #     running_loss = 0.0
#     test_loop(test_load,model)

# print('Finished Training')